---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: did-finder-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: did-finder-demo
  template:
    metadata:
      labels:
        app: did-finder-demo
    spec:
      containers:
      - name: did-finder-demo
        image: servicex-did-finder-demo:latest
        imagePullPolicy: Never
        env:
          - name: INSTANCE_NAME
            value: pondd-servicex
        args:
          - --rabbit-uri
          - amqp://user:leftfoot1@pondd-servicex-rabbitmq:5672
